"""Vendor the web fonts, once, into docs/fonts/.

Run by hand and the results committed, like generate/bibframe.rdf: the site
build stays offline and a visitor makes no request to anyone but the host.
Both families are under the SIL Open Font License, which permits this and
requires the licence to travel with them -- docs/fonts/OFL.txt.

Literata carries the prose because this is documentation about bibliographic
description, and a face designed for reading books is the honest choice for
it; IBM Plex Mono carries the JSON, the field labels and the ISBD delimiters.
Neither is the sans-serif every API reference is set in.

Cyrillic is not optional here. The shape page shows one title in two scripts,
which is the example that makes the case for language tags, and it is inside a
code block -- so the mono needs the subset as much as the serif does.
"""

import re
import subprocess
import sys
from pathlib import Path

FONTS = Path(__file__).resolve().parent.parent / "docs" / "fonts"

# Three static instances of Literata rather than the variable font. The
# variable files carry the whole opsz 7..72 and wght 200..900 range and are
# 108K per subset; these are a third of that, and a documentation site uses
# three weights. opsz 14 is the reading size the prose is set at.
FAMILIES = {
    "literata": "Literata:ital,opsz,wght@0,14,400;0,14,600;1,14,400",
    "plex-mono": "IBM+Plex+Mono:wght@400;600",
}
WANTED = ("latin", "latin-ext", "cyrillic")
AGENT = (
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
)


def fetch(url: str) -> bytes:
    done = subprocess.run(
        ["curl", "-sSfL", "-H", f"User-Agent: {AGENT}", url],
        capture_output=True,
        check=False,
    )
    if done.returncode:
        raise SystemExit(f"could not fetch {url}: {done.stderr.decode()[:200]}")
    return done.stdout


def main() -> None:
    FONTS.mkdir(parents=True, exist_ok=True)
    faces: list[str] = []
    for name, spec in FAMILIES.items():
        css = fetch(f"https://fonts.googleapis.com/css2?family={spec}&display=swap")
        css = css.decode()
        # Google emits one @font-face per subset, each preceded by a comment
        # naming it. The comment is the only thing that says which subset a
        # unicode-range belongs to, so it is what gets matched on.
        blocks = re.findall(r"/\* (\S+) \*/\s*(@font-face \{.*?\})", css, re.DOTALL)
        kept = 0
        for subset, block in blocks:
            if subset not in WANTED:
                continue
            url = re.search(r"url\((https://[^)]+\.woff2)\)", block)
            if not url:
                continue
            style = re.search(r"font-style: (\w+)", block)
            weight = re.search(r"font-weight: ([\d ]+)", block)
            slug = f"{name}-{subset}-{style.group(1) if style else 'normal'}"
            if weight and " " not in weight.group(1).strip():
                slug += f"-{weight.group(1).strip()}"
            path = FONTS / f"{slug}.woff2"
            path.write_bytes(fetch(url.group(1)))
            faces.append(
                re.sub(
                    r"url\(https://[^)]+\.woff2\)",
                    f"url(fonts/{path.name})",
                    block,
                ).replace("@font-face {", "@font-face {\n  font-display: swap;")
            )
            kept += 1
        print(f"  {name}: {kept} files")

    (FONTS / "faces.css").write_text(
        "/* Generated by generate/fonts.py. The woff2 files beside this are\n"
        "   vendored from Google Fonts under the OFL; see OFL.txt. */\n\n"
        + "\n\n".join(faces)
        + "\n"
    )
    total = sum(p.stat().st_size for p in FONTS.glob("*.woff2"))
    print(f"  {total / 1024:.0f}K of woff2 in {FONTS.relative_to(Path.cwd())}")


if __name__ == "__main__":
    sys.exit(main())
